language: node_js

env:
  - DATABASE_URL=postgresql://codex:pg123@localhost:5432/greetingsDB

node_js:  
  - "14.4.0"

before_script:
  - psql -c 'create database  greetingsDB;' -U codex
  - psql -U codex -d greetingsDB -a -f table.sql

services:
  - postgresql